### ISSUE TITLE
停止使用 会存在一直处于释放中的状态

### ISSUE THREAD

**Issue by pengchenglin** [openatx/atxserver2#11]
![image](https://user-images.githubusercontent.com/20560050/57205755-57115300-6ff3-11e9-83ba-b1f1a6b116f4.png)

**Comment by codeskyblue** [comment]
看日志是atxserver2跟provider通信错误了，provider有什么错误日志吗

**Comment by pengchenglin** [comment]
应该是网络的问题 我当时好像切了个Wi-Fi


|
林鹏程
m170587788@163.com
|

签名由 网易邮箱大师 定制

在2019年05月11日 06:55，shengxiang 写道：

看日志是atxserver2跟provider通信错误了，provider有什么错误日志吗

**Comment by codeskyblue** [comment]
duplicated with #14
