### ISSUE TITLE
无法加载屏幕

### ISSUE THREAD

**Issue by fishasen** [openatx/atxserver2#17]

**Comment by fishasen** [comment]
![image](https://user-images.githubusercontent.com/17735370/58010793-97102400-7b23-11e9-87d4-49c935334dd3.png)
1、屏幕提示同步中断（一直无法加载）
2、点击任意按钮，url访问是eth0，但是主机无法与该地址通信
3、容器启动地址是关联eth0

主机地址：192.168.99.1
宿主机eth0：10.0.2.15
宿主机eth1：192.168.99.102

怎么修改让容器关联eth1？

**Comment by 201905270246** [comment]
@fishasen 
你好， 请问遇到的是类似https://github.com/openatx/atxserver2-ios-provider/issues/14
如何解决的？
