### ISSUE TITLE
/app/install访问的3500端口不存在

### ISSUE THREAD

**Issue by ruberzhu** [openatx/atxserver2#18]
上传.apk后，返回的http://10.33.154.109:3500/app/install?udid=UYT5T18307005478，报500

[](url)
<img width="964" alt="屏幕快照 2019-06-05 下午6 05 40" src="https://user-images.githubusercontent.com/6029556/58948738-6388f700-87bd-11e9-9a76-437a5daea94a.png">

**Comment by codeskyblue** [comment]
都返回500了，肯定存在呀。看看provider办什么错

**Comment by ruberzhu** [comment]
已经解决，和nginx配置有关，需要在nginx的反向代理模块增加如下配置。
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
