### ISSUE TITLE
设备屏幕同步中断

### ISSUE THREAD

**Issue by onlinesen** [openatx/atxserver2#22]
所有步骤都完成了，看起来也没什么问题，设备都已经在线，但没有屏幕显示
提示“设备屏幕同步中断“
请问如何调试？

**Comment by codeskyblue** [comment]
看看provider是不是有什么错误日志

**Comment by onlinesen** [comment]
目前已经移到UBUNTU上去了，是正常的，有空我再看看windows是什么情况吧。
