### ISSUE TITLE
Version in ".\docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by HakunamatataLeo** [openatx/atxserver2#24]
[31mERROR[0m: Version in ".\docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

**Comment by codeskyblue** [comment]
把docker升级下就好了
