### ISSUE TITLE
远程 provider 下设备截图失败

### ISSUE THREAD

**Issue by HBoPRC** [openatx/atxserver2#28]
server 服务器在 10.44；远程 provider 机器是 2.139；截图 URL 地址是 40.28；实际截图操作没有获取到图片
![QC 0801 174712](https://user-images.githubusercontent.com/37980474/62284062-7d754c00-b485-11e9-941e-a4a25dc346bf.jpg)

**Comment by codeskyblue** [comment]
这个是修改版的atxserver2，我记得现在代码里面还没有这个功能

**Comment by HBoPRC** [comment]
> 这个是修改版的atxserver2，我记得现在代码里面还没有这个功能

我们自己改了下，把截图直接显示在这个页签下了；就是直接用的原来那个下载截图的URL

**Comment by codeskyblue** [comment]
那你看看是不是请求路径错了，这个问题一般都很好修

**Comment by HBoPRC** [comment]
找到原因了，是魅族手机的问题，直连截图也不行
好像是atx挂了，APP 起不起来
机型：魅族 魅蓝 S6

**Comment by HBoPRC** [comment]
找到根本原因了：手机上 uiautomator 没启，直接调的 minicap 截图失败，手动启了 uiautomator 截图就正常了
