### ISSUE TITLE
怎样在本地，使用远程设备的音视频？

### ISSUE THREAD

**Issue by dgzGitHub** [openatx/atxserver2#39]
手机设备A，在远程机B中通过链接打开，怎样使远程机的摄像头，替换为设备A的摄像头和麦克风，说的有点乱，但是你懂得吧><
公司做视频直播的，所以有这个需求

**Comment by codeskyblue** [comment]
我暂时也没有什么方案，也就想到一个把手机连到电脑的音频输入口，然后PCM传递到浏览器上

**Comment by dgzGitHub** [comment]
好吧，感觉这是一个痛点
