### ISSUE TITLE
环境问题 

### ISSUE THREAD

**Issue by za123** [openatx/atxserver2#4]
atxserver2的tornado包版本与项目 atxserver2-android-provider的tornado版本不一样，他们需要分开环境吗

**Comment by StarMX** [comment]
你可以这样理解，atxserver2是中心控制器，但是你有N部手机在不同房间里，你在每个房间加一个android-provider这样通过atxserver2就能管理各个不同房间里的手机，建议使用python -m venv 建立虚拟运行环境
