### ISSUE TITLE
使用docker无法部署？

### ISSUE THREAD

**Issue by PikachuCN** [openatx/atxserver2#49]
在win和lunix 直接docker-compose up
都会出现无法部署
windows是找不到数据库

rethinkdb_1  | error: Error in src/serializer/log/log_serializer.cc at line 81:
rethinkdb_1  | error: Could not rename database file /data/rethinkdb_data/tmp/metadata.create to permanent location /data/rethinkdb_data/metadata (Device or resource busy)
rethinkdb_1  | error: Backtrace:
rethinkdb_1  | error: Sat Mar  7 12:47:36 2020
lunix是

ERROR: for atxserver2_web_1  Cannot start service web: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"scripts/wait-for-db.sh\": permission denied": unknown

ERROR: for web  Cannot start service web: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"scripts/wait-for-db.sh\": permission denied": unknown

![Alt Text](https://pic.downk.cc/item/5e639f9998271cb2b8ee2e33.png)

**Comment by codeskyblue** [comment]
Windows我现在没有机器可以测试。
Linux上的处理方法倒是很简单。就是 chmod +x scripts/wait-for-db.sh 然后在 docker-compose up

**Comment by ZhinanSu** [comment]
chmod +x scripts/wait-for-db.sh 添加了权限还是报这个错误
![8P`EHCJ9ASE0S`ACTWZKMVL](https://user-images.githubusercontent.com/31877555/77036651-9453b900-69ea-11ea-9b15-9ad92ed510a1.png)

**Comment by ZhinanSu** [comment]
chmod +x scripts/wait-for-db.sh  添加了权限还是报错
![image](https://user-images.githubusercontent.com/31877555/77036716-b64d3b80-69ea-11ea-8596-cc085aecee6c.png)
