### ISSUE TITLE
adb connnect 连接设备，执行atxserver2-android-provider的时候   会skip remote deivce

### ISSUE THREAD

**Issue by snowof** [openatx/atxserver2#53]
![image](https://user-images.githubusercontent.com/9877256/82192907-3595b780-9927-11ea-8c46-fbcbcf15db95.png)
有人遇到过么，如何解决？

**Comment by gamecln277** [comment]
加參數
sudo docker run --rm --privileged -v /dev/bus/usb:/dev/bus/usb --net host ${IMAGE} python main.py --server ${SERVER_URL} --allow-remote

**Comment by snowof** [comment]
> 加参数
> sudo docker run --rm --privileged -v / dev / bus / usb：/ dev / bus / usb --net host $ {IMAGE} python main.py --server $ {SERVER_URL} --allow-remote

感谢成功了
