### ISSUE TITLE
ATX 不支持 iOS10和iOS 15

### ISSUE THREAD

**Issue by coolalexhuang** [openatx/atxserver2#82]
连接以下设备失败, 使用Appium WDA可以成功通过安装
iPhone5c - iOS 10.3.3, 
iPhoneXS - iOS 15

**Comment by coolalexhuang** [comment]
> 连接以下设备失败, 使用Appium WDA可以成功通过安装 iPhone5c - iOS 10.3.3, iPhoneXS - iOS 15

iOS15重试后可以支持，iOS10目前还不能支持

**Comment by chenhengjie123** [comment]
iOS 10 是因为 wda 底层用到的屏幕流私有 api 是 ios 11 开始才有，因此 ios 10 用不了。此问题暂时无解。
