### ISSUE TITLE
HUAWEI P20连接报错未知错误，日志截图上面

### ISSUE THREAD

**Issue by chenwenkun** [openatx/atxserver2#9]
![image](https://user-images.githubusercontent.com/42236131/55929821-225ae780-5c51-11e9-8c5d-72669b4cff6a.png)

**Comment by codeskyblue** [comment]
我加了点 traceback信息
![image](https://user-images.githubusercontent.com/3281689/55930878-eb3b0500-5c55-11e9-9c32-926c0091d1cd.png)

你更新下 atxserver2-android-provider 重新输出

**Comment by codeskyblue** [comment]
ping..

**Comment by codeskyblue** [comment]
有问题请再重新reopen
