### ISSUE TITLE
代码问题，为什么html中的vue变量写法是{{!}}，要加一个感叹号

### ISSUE THREAD

**Issue by HongFei1998** [openatx/atxserver2#95]
如标题所提问，为什么atxserver中的vue写法如此特殊

**Comment by codeskyblue** [comment]
这个主要是 tornado的语法，参考 https://www.tornadoweb.org/en/stable/template.html#syntax-reference
`{{!foo}}`  会被转义成 `{{foo}}` 供vue使用

**Comment by HongFei1998** [comment]
好的收到，多谢解答
